Numpy library is a general-purpose library in Python. It provides a high performance multidimensional array object, and tools for working with these arrays.

What is an array?
An array is a data structure that stores multiple values of the same data type. In Python, arrays are implemented as lists.While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to a single data type.

In [1]:
import numpy as np

In [5]:
my_lst=[1, 2, 3, 4, 5]
print(type(my_lst))
arr=np.array(my_lst)
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(5,)

In [7]:
l1=[1,2,3,4,5]
l2=[6,7,8,9,10]
l3=[11,12,13,14,15]

arr=np.array([l1, l2, l3])


In [8]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
arr.shape

(3, 5)

In [10]:
arr.size


15

In [11]:
arr.itemsize

8

In [15]:
arr.diagonal(offset=4)

array([5])

In [9]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [18]:
narr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(narr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
narr.diagonal(offset=0)
narr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
arr.ndim

2

In [28]:
sarr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(sarr)
sarr.ndim
sarr.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

Indexing

In [12]:
arr=np.array([1,2,3,9,4,4,4,3,3,4,55,9])

In [15]:
arr

array([ 1,  2,  3,  9,  4,  4,  4,  3,  3,  4, 55,  9])

In [16]:
arr[[9]]

array([4])

In [18]:
arr[1:8]

array([2, 3, 9, 4, 4, 4, 3])

In [19]:
arr=[[1,2,3,3],[4,5,5,6],[7,8,9,10]]
arr=np.array(arr)
arr

array([[ 1,  2,  3,  3],
       [ 4,  5,  5,  6],
       [ 7,  8,  9, 10]])

In [20]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [23]:
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [25]:
np.linspace(1,100,20)

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [26]:
##copy function and broadcasting function
arr[3:]=100
arr

array([  0,   2,   4, 100, 100])

In [27]:
arr1=arr

In [28]:
arr1[3:]=500
arr1

array([  0,   2,   4, 500, 500])

In [29]:
arr1=arr.copy()

In [30]:
arr1

array([  0,   2,   4, 500, 500])

In [31]:
arr2=[1,2,3,4,5]
arr<3

array([ True,  True, False, False, False])

In [37]:
#create an array and reshape it
arr=np.arange(0,10).reshape(5,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])